import os
import opentimelineio as otio
from pathlib import Path
from typing import List, Dict

class ExportEngine:
    """Engine for generating professional post-production export formats."""

    def __init__(self, output_dir: str = "outputs"):
        self.output_dir = Path(output_dir)

    def generate_edl(self, project_id: str, actor_id: str, actor_name: str, clips: List[Dict], source_video: str) -> str:
        """Generate a standard CMX 3600 EDL for a set of clips."""
        export_path = self.output_dir / project_id / f"{actor_id}.edl"
        export_path.parent.mkdir(parents=True, exist_ok=True)

        video_name = Path(source_video).name
        
        with open(export_path, "w") as f:
            f.write("; CMX 3600 EDL Export\n")
            f.write(f"; Actor: {actor_name}\n")
            f.write(f"; Source: {video_name}\n")
            f.write(f"; Generated by Tycho\n")
            f.write(";\n")
            f.write("001  AX       V     C        00:00:00:00 00:00:00:00 01:00:00:00 01:00:00:00\n")
            f.write("* FROM CLIP NAME: {actor_name} Sizzle Reel\n")
            f.write(";\n")
            
            for i, clip in enumerate(clips, start=1):
                start_frames = int(clip['start'] * 24)
                end_frames = int(clip['end'] * 24)
                duration_frames = end_frames - start_frames
                
                # Convert to HH:MM:SS:FF format
                def frames_to_timecode(frames):
                    h = frames // (24 * 3600)
                    frames %= (24 * 3600)
                    m = frames // (24 * 60)
                    frames %= (24 * 60)
                    s = frames // 24
                    f = frames % 24
                    return f"{h:02d}:{m:02d}:{s:02d}:{f:02d}"
                
                source_in = frames_to_timecode(0)
                source_out = frames_to_timecode(duration_frames)
                record_in = frames_to_timecode(i * 100)
                record_out = frames_to_timecode(i * 100 + duration_frames)
                
                f.write(f"{i:03d}  AX       V     C        {source_in} {source_out} {record_in} {record_out}\n")
                f.write(f"* FROM CLIP NAME: Clip_{i}_{actor_name} ({clip['start']:.1f}s - {clip['end']:.1f}s)\n")
        
        return str(export_path)

    def generate_aaf(self, project_id: str, actor_id: str, actor_name: str, clips: List[Dict], source_video: str) -> str:
        """Generate an AAF-like XML for Avid/Premiere import."""
        export_path = self.output_dir / project_id / f"{actor_id}.aaf"
        export_path.parent.mkdir(parents=True, exist_ok=True)

        video_name = Path(source_video).name
        
        # Generate AAF-like XML (simplified AAF structure)
        with open(export_path, "w") as f:
            f.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
            f.write("<!DOCTYPE AAF SYSTEM \"aaf.dtd\">\n")
            f.write("<AAF>\n")
            f.write(f"  <Header>\n")
            f.write(f"    <ProductName>Tycho AAF Export</ProductName>\n")
            f.write(f"    <CompanyName>Tycho AI</CompanyName>\n")
            f.write(f"    <ProductVersion>1.0</ProductVersion>\n")
            f.write(f"    <ProjectName>{actor_name}_Avid_Export</ProjectName>\n")
            f.write(f"  </Header>\n")
            f.write(f"  <Composition>\n")
            f.write(f"    <Timeline name=\"{actor_name}_Sizzle_Reel\">\n")
            f.write(f"      <VideoTrack>\n")
            
            for i, clip in enumerate(clips):
                duration = clip['end'] - clip['start']
                f.write(f"        <Clip id=\"clip_{i}\">\n")
                f.write(f"          <Name>Clip_{i}_{actor_name}</Name>\n")
                f.write(f"          <Source>{video_name}</Source>\n")
                f.write(f"          <StartTime>{clip['start']:.6f}</StartTime>\n")
                f.write(f"          <EndTime>{clip['end']:.6f}</EndTime>\n")
                f.write(f"          <Duration>{duration:.6f}</Duration>\n")
                f.write(f"        </Clip>\n")
            
            f.write(f"      </VideoTrack>\n")
            f.write(f"    </Timeline>\n")
            f.write(f"  </Composition>\n")
            f.write(f"</AAF>\n")
        
        return str(export_path)
